
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<link rel="stylesheet" type="text/css" class="norm" href="style.css">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>ASTR 3510 Handouts </title>
<center>
<h1> ASTR 3510 Handouts </h1>
</center>
</head>
<center>
    <table align="center" width=800><tr><td>
<center>
<!--<h3><a href="Syllabus.doc"> Syllabus.doc</a>-->
<h3><a href="handouts/Syllabus.pdf"> Syllabus.pdf</a>
<h3><a href="handouts/Photometry_CCSs_22oct06_Romanishin.pdf"> Photometry CCDs Romanishin.pdf</a>
<h3><a href="handouts/unixworksheet.txt">UNIX worksheet</a>
<h3><a href="handouts/optics_notes.pdf">Optics Notes (9/1/09)</a>
<h3><a href="handouts/reduction_example.txt">Example IRAF Image Reduction </a>
<h3><a href="http://eta.colorado.edu/filtersets.htm">Adam's list of astronomical filters</a>
    
    <!--
    <h3><a class="special" href="handouts/syllabus.pdf">Syllabus (Bally)</a></h3>
    <h3><a class="special" href="handouts/gratingreview.pdf">Grating Review Sheet (Ginsburg)</a></h3>
    <h3><a class="special" href="handouts/exposuretime2article.pdf">Exposure Time Calculation Examples (Ginsburg)</a></h3>
    <h3><a class="special" href="handouts/Spectrograph_design_ex.pdf">Grating Lecture (Bally)</a></h3>
    <h3><a class="special" href="handouts/lectures_september2008.pdf">Lectures Powerpoint - September update (Bally)</a></h3>
    <h3><a class="special" href="handouts/lectures_october2008.pdf">Lectures Powerpoint - October update (Bally)</a></h3>
    -->

<br><br><br><hr>
<?php include 'navbar.php';?>


</table>

</html>
