
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<link rel="stylesheet" type="text/css" class="norm" href="style.css">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>ASTR 3510 Homeworks </title>
<center>
<h1> ASTR 3510 Homeworks </h1>
</center>
</head>
<center>
    <table align="center" width=800><tr><td>
<center>

<h3>[ <a href="handouts/HW1.doc"> HW1.doc</a> ] [ <a href="handouts/HW1.pdf"> HW1.pdf</a> ]</h3>
<h3>[ <a href="handouts/HW2.doc"> HW2.doc</a> ] [ <a href="handouts/HW2_soln.pdf">HW2 solutions</a> ]</h3> 
<h3>[ <a href="handouts/HW3.doc"> HW3.doc</a> ] [ <a href="handouts/HW3_soln.pdf">HW3 solutions</a> ]</h3> 
<h3>[ <a href="handouts/midterm_answers.doc">Midterm Solutions</a> ]</h3> 
    

<br><br><br><hr>
<?php include 'navbar.php';?>


</table>

</html>
