<html>
<!--<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">-->
<link rel="stylesheet" type="text/css" href="style.css">
<!--<body text="#FFFFFF" bgcolor="#000000" vlink="#0000FF" link="#00FFFF">-->
<title> Astronomy 3510: Observation and Instrumentation I: Imaging </title>
<body> 
		<head><h1><center> ASTR 3510 </center></h1></head>
<!--		<center><font size="2"> Think an observational page needs some images?  Send me recommendations.</font>
<br> <center><h3> Office Hours:</h3>
                By appointment, or 11-12 MW in C329 for Adam and 2-3 PM WR in C323A for John.  Adam's e-mail addresses are adam.ginsburg@colorado.edu and keflavich@gmail.com.-->
<center>
    <table align="center" width=800><tr><td>
<center>
 <h3><a href="observing.shtml" class="special">Observing Signup Page</a></h3>
 <h3><a href="calendar.phtml" class="special">Course Calendar</a></h3>
 <h3><a href="labs.phtml" class="special">Labs / SBO instructions</a></h3>
 <h3><a href="handouts.phtml" class="special">Handouts / Class Notes</a></h3>
 <h3><a href="homeworks.phtml" class="special">Homeworks</a></h3>
<hr>

<?php include 'navbar.php';?>
<br>

<small>
<br>  Created 8/25/09 by <a class="hidden" href="http://casa.colorado.edu/~ginsbura">Adam Ginsburg</a> (adam.ginsburg@colorado.edu)
<br> Class taught by <a href="http://casa.colorado.edu/~bally/">John Bally</a>
</small>

</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37306139-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>


