<html><body><phtml>
<!--<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/phtml; charset=windows-1252">-->
<link href="style.css" rel="stylesheet" type="text/css"/>
<!--<body text="#FFFFFF" bgcolor="#000000" vlink="#0000FF" link="#00FFFF">-->
<title> Astronomy 3520: Lab 3 and 4 signup </title>
<h1><center> ASTR 3520: Lab 3 and 4 signup</center></h1>
<br/>
<br/>                Stars:
<br/>                Group 1 (Thomas, Kyle, Matt, Alana):
<br/>                Eta Cass
<br/>                Beta Cyg
<br/>                Group 2 (Kim, Elizabeth, Elin):
<br/>                10 Lac
<br/>                Iota Peg
<br/>                Group 3 (Julia, Stephanie, David, John):
<br/>                Gamma Cyg
<br/>                Alpha Cyg
<br/>                Group 4 (Heather, Justin, Giada, Deno - Astrosaurs):
<br/>                Beta And
<br/>                Gamma And
<br/>
<br/>                PN:
<br/>                Group 1: NGC 6543
<br/>                Group 2: Ring Nebula
<br/>                Group 3: NGC 6884
<br/>                Group 4: NGC 7027

<br/><br/><br/><a class="special" href="index.phtml">ASTR3520 home</a>
<br/> <p> Created 10/9/07 by <a class="hidden" href="http://casa.colorado.edu/~ginsbura">Adam Ginsburg</a> (adam.ginsburg@colorado.edu)

                </p></phtml></body><script src="../googleanalytics.js" type="text/javascript"></script></html>