<html>
<!--<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/phtml; charset=windows-1252">-->
<link rel="stylesheet" type="text/css" href="style.css">
<!--<body text="#FFFFFF" bgcolor="#000000" vlink="#0000FF" link="#00FFFF">-->
<title> Astronomy 3510: SBO 24 inch camera </title>
<body> 
<head><h1><center> ASTR 3510: SBO Camera </center></h1></head>
<table align="center" width=800><tr><td>
<br>
Opening Procedure for the SBO Camera:
   <ol><li>Open telescope with normal opening procedure.  Can leave dome closed at start.
       <li> Turn on the telescope electronics (the key at the bottom of the telescope)
       <li> Turn on the leftmost computer.  It is the camera controller.
       <li> The first time you use the camera software, run the command:
<br> <code> cp /home/shared/astr3510/apogee/.apccd.ini ~/ </code>
       <li>Run the command <br><code>/home/shared/astr3510/apogee/startapogee</code><br>  If this results in a segmentation fault, close ds9 and run it again.  You may need to try 2-3 times; this is an error we are trying to fix.
       <li>Find target in eyepiece, adjust to align CCD to target
   </ol>
<br>
<a href="speccam_userguide.pdf">Users guide for the long-format camera software</a>
<br><br><br>
<?php include 'navbar.php';?>
<br> <font size=1>Created 08/31/09 by <a class="hidden" href="http://casa.colorado.edu/~ginsbura">Adam Ginsburg</a> (adam.ginsburg@colorado.edu)</font>

</body>
</html>
