<html><body><pphtml>
<meta content="en-us" http-equiv="Content-Language"/>
<link class="norm" href="style.css" rel="stylesheet" type="text/css"/>
<meta content="text/pphtml; charset=utf-8" http-equiv="Content-Type"/>
<title>ASTR 3510 Labs </title>
<center>
<h1> ASTR 3510 Labs </h1>
</center>
<center>
<table align="center" width="800"><tr><td>
<center>
Lab 0 was getting checked out on the 24 inch.  
<br/> <br/> Please read the <a href="imager.phtml"> instructions for camera start up</a> and remember to sign up on the <a href="observing.shtml">observing calendar</a>
<br/><br/>
<a href="handouts/Lab_1.doc"> Lab 1 </a><br/>
<a href="handouts/Lab_2.doc"> Lab 2 </a><br/>
<!--<a href="handouts/Lab_3.doc"> Lab 3 </a><br>-->
<a href="lab3.phtml">Lab 3 </a><br/>
<a href="handouts/Lab_4.doc"> Lab 4 </a><br/>
<a href="handouts/Lab_5.doc"> Lab 5 </a><br/>
</center></td></tr></table>
<br/><br/><br/>
</center></pphtml></body><script src="../googleanalytics.js" type="text/javascript"></script></html>