<pphtml>

<head>
<meta http-equiv="Content-Language" content="en-us">
<link rel="stylesheet" type="text/css" class="norm" href="style.css">
<meta http-equiv="Content-Type" content="text/pphtml; charset=windows-1252">
<title>ASTR 3510 Labs </title>
<center>
<h1> ASTR 3510 Labs </h1>
</center>
</head>
<center>
    <table align="center" width=800><tr><td>
                <center>
Lab 0 was getting checked out on the 24 inch.  
<br> <br> Please read the <a href="imager.phtml"> instructions for camera start up</a> and remember to sign up on the <a href="observing.shtml">observing calendar</a>
<br><br>
<a href="handouts/Lab_1.doc"> Lab 1 </a><br>
<a href="handouts/Lab_2.doc"> Lab 2 </a><br>
<!--<a href="handouts/Lab_3.doc"> Lab 3 </a><br>-->
<a href="lab3.phtml">Lab 3 </a><br>
<a href="handouts/Lab_4.doc"> Lab 4 </a><br>
<a href="handouts/Lab_5.doc"> Lab 5 </a><br>
    </table>

<br><br><br>
<?php include 'navbar.php';?>

</pphtml>
