 M82
Duration    001000
Name    M82
RA2000    095552.1900
DEC2000    694048.800
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    C
BandCode(2)    C
BandCode(3)    C
BandCode(4)    C
BandwidthCode(1)    0
BandwidthCode(2)    0
BandwidthCode(3)    0
BandwidthCode(4)    0
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    4885.100000
SkyFrequency(2)    4835.100000
SkyFrequency(3)    4885.100000
SkyFrequency(4)    4835.100000
ObservingMode      
IntegrationTime    10
 M82X
Duration    001000
Name    M82
RA2000    095552.1900
DEC2000    694048.800
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    X
BandCode(2)    X
BandCode(3)    X
BandCode(4)    X
BandwidthCode(1)    0
BandwidthCode(2)    0
BandwidthCode(3)    0
BandwidthCode(4)    0
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    8435.100000
SkyFrequency(2)    8485.100000
SkyFrequency(3)    8435.100000
SkyFrequency(4)    8485.100000
ObservingMode      
IntegrationTime    10
 M82L
Duration    001000
Name    M82
RA2000    095552.1900
DEC2000    694048.800
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    L
BandCode(2)    L
BandCode(3)    L
BandCode(4)    L
BandwidthCode(1)    0
BandwidthCode(2)    0
BandwidthCode(3)    0
BandwidthCode(4)    0
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    1464.900000
SkyFrequency(2)    1385.100000
SkyFrequency(3)    1464.900000
SkyFrequency(4)    1385.100000
ObservingMode      
IntegrationTime    10
 3C286
Name    3C286
RA2000    133108.2881
DEC2000    303032.960
TypeOfEpoch    C
ReferencePointing     
ObservingMode      
IntegrationTime    10
Comment    Absolute Flux Calibrator
