<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phtml PUBLIC "-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN"
        "HTMLFiles/xphtml-math11-f.dtd">

<!-- Created by Wolfram Mathematica 6.0 -->

<phtml xmlns="http://www.w3.org/1999/xphtml">
<head>
 <title>
  gratingreview
 </title>
 <link href="HTMLFiles/Default.css" rel="stylesheet" type="text/css"/>
</head>

<body>

<p class="Text">
 Astronomy 3520: Grating Review Sheet
</p>



<p class="Graphics">
 <img src='HTMLFiles/gratingreview_1.gif' alt='"gratingreview_1.gif"' width='384' height='300' style='vertical-align:middle'/>
</p>

<p class="Text">
 For a reflection grating, n&lambda; = d(sin &alpha; &plusmn; sin &beta;), where &alpha; and &beta; are the incident and reflected angles respectively
</p>



<p class="Input">
 <img src='HTMLFiles/gratingreview_2.gif' alt='"gratingreview_2.gif"' width='4' height='16' style='vertical-align:middle'/>
</p>

<p class="Graphics">
 <img src='HTMLFiles/gratingreview_3.gif' alt='"gratingreview_3.gif"' width='420' height='231' style='vertical-align:middle'/>
</p>

<p class="Text">
 For a transmission grating, however, n&lambda; = d sin &theta; because we assume the incident angle is 0. 
</p>



<p class="Text">
 <img src='HTMLFiles/gratingreview_4.gif' alt='"gratingreview_4.gif"' width='527' height='209' style='vertical-align:middle'/>
</p>

<p class="Text">
 <img src='HTMLFiles/gratingreview_5.gif' alt='"gratingreview_5.gif"' width='598' height='188' style='vertical-align:middle'/>
</p>

<p class="Text">
 To derive the resolution of a telescope, we start with the dispersion equation n&lambda; = d sin &theta;
</p>



<p class="Input">
 <img src='HTMLFiles/gratingreview_6.gif' alt='"gratingreview_6.gif"' width='112' height='50' style='vertical-align:middle'/>
</p>

<p class="Text">
 We also know that d&theta; = <span><span><img src='HTMLFiles/gratingreview_7.gif' alt='"gratingreview_7.gif"' width='35' height='33' style='vertical-align:middle'/></span></span>where x is the size of the image on your focal plane (in general, you probably want your smallest resolution element to be nyquist sampled, so x should be twice the pixel size) and <span><span><img src='HTMLFiles/gratingreview_8.gif' alt='"gratingreview_8.gif"' width='22' height='15' style='vertical-align:middle'/></span></span> is the focal length of your camera optics.&nbsp;&nbsp;This can be recovered from our familiar diagram:
</p>



<p class="Graphics">
 <img src='HTMLFiles/gratingreview_9.gif' alt='"gratingreview_9.gif"' width='723' height='92' style='vertical-align:middle'/>
</p>

<p class="Text">
 where in this case, the size on the focal plane is x, the focal length is the camera focal length, and &theta; is d&theta;
</p>



<p class="Text">
 <img src='HTMLFiles/gratingreview_10.gif' alt='"gratingreview_10.gif"' width='820' height='92' style='vertical-align:middle'/>
</p>

<p class="Graphics">
 <img src='HTMLFiles/gratingreview_11.gif' alt='"gratingreview_11.gif"' width='811' height='477' style='vertical-align:middle'/>
</p>

<p class="Text">
 In the calculations below, all units will be centimeters
</p>



<p class="CellLabel">
 In[12]:=
</p>



<p class="Input">
 <img src='HTMLFiles/gratingreview_12.gif' alt='"gratingreview_12.gif"' width='148' height='243' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[12]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_13.gif' alt='"gratingreview_13.gif"' width='42' height='30' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[13]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_14.gif' alt='"gratingreview_14.gif"' width='28' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[14]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_15.gif' alt='"gratingreview_15.gif"' width='49' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[15]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_16.gif' alt='"gratingreview_16.gif"' width='24' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[16]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_17.gif' alt='"gratingreview_17.gif"' width='35' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[17]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_18.gif' alt='"gratingreview_18.gif"' width='56' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[18]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_19.gif' alt='"gratingreview_19.gif"' width='7' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[19]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_20.gif' alt='"gratingreview_20.gif"' width='84' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[20]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_21.gif' alt='"gratingreview_21.gif"' width='77' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[21]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_22.gif' alt='"gratingreview_22.gif"' width='85' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 In[22]:=
</p>



<p class="Input">
 <img src='HTMLFiles/gratingreview_23.gif' alt='"gratingreview_23.gif"' width='47' height='30' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[22]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_24.gif' alt='"gratingreview_24.gif"' width='49' height='15' style='vertical-align:middle'/>
</p>

<p class="Text">
 What if we had been given a different value?&nbsp;&nbsp;Say we knew the central wavelength &lambda; = 4400 &Aring; instead of the angle &theta; :
</p>



<p class="CellLabel">
 In[66]:=
</p>



<p class="Input">
 <img src='HTMLFiles/gratingreview_25.gif' alt='"gratingreview_25.gif"' width='171' height='277' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[66]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_26.gif' alt='"gratingreview_26.gif"' width='42' height='30' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[67]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_27.gif' alt='"gratingreview_27.gif"' width='28' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[68]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_28.gif' alt='"gratingreview_28.gif"' width='49' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[69]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_29.gif' alt='"gratingreview_29.gif"' width='35' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[70]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_30.gif' alt='"gratingreview_30.gif"' width='7' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[71]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_31.gif' alt='"gratingreview_31.gif"' width='49' height='30' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[72]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_32.gif' alt='"gratingreview_32.gif"' width='56' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[73]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_33.gif' alt='"gratingreview_33.gif"' width='49' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[74]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_34.gif' alt='"gratingreview_34.gif"' width='77' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[75]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_35.gif' alt='"gratingreview_35.gif"' width='85' height='15' style='vertical-align:middle'/>
</p>

<p class="CellLabel">
 Out[76]=
</p>



<p class="Output">
 <img src='HTMLFiles/gratingreview_36.gif' alt='"gratingreview_36.gif"' width='49' height='15' style='vertical-align:middle'/>
</p>

<p class="Text">
 So the resolution is higher (3000), but our camera has to be at an angle of 45 degrees instead of 35 degrees for the first order 
</p>



<hr/>

<table><tr>
<td style='font-family: Helvetica; font-size: 10px; width: 100%'>Created by
 <a href="http://www.wolfram.com/products/mathematica"><span style='font-style: italic'>Wolfram Mathematica 6.0</span></a>
 &nbsp;(08 November 2007)</td>
<td><img src='http://www.w3.org/Icons/valid-xphtml11.gif'
 alt='Valid XHTML 1.1!' height='31' width='88'/></td>
</tr></table>
</body>

</phtml>
