<phtml>

<head>
<meta http-equiv="Content-Language" content="en-us">
<link rel="stylesheet" type="text/css" class="norm" href="style.css">
<meta http-equiv="Content-Type" content="text/phtml; charset=windows-1252">
<title>ASTR 3510 Links </title>
<center>
<h1> ASTR 3510 Links </h1>
</center>
</head>
<center>
    <table align="center" width=800><tr><td>

<br> <h4> External Links: </h4>
<dl>
    <br><a href="http://www.twilightlandscapes.com/IRAFtutorial/">Josh Walawender's IRAF tutorial</a>
    <dt><a href="http://eta.colorado.edu/filtersets.htm">Adam's list of astronomical filters</a>
    <dt><a href="http://www.astro.wisc.edu/~dolan/constants.html">Astronomical/Physical constants in CGS</a>
    <dt><a href="http://isthe.com/chongo/tech/astro/HR-temp-mass-table-byhrclass.html">Stellar Classification Table</a>
    <dt><a href="http://cleardarksky.com/c/SomBoschObCOkey.html">SBO Clear Sky Clock</a>
    <dt><a href="http://lyra.colorado.edu/sbo/">SBO Website</a>
    <dt><a href="http://iraf.noao.edu/docs/docmain.html">IRAF Project Website Documentation</a>
    <dt><a href="http://www.iraf.net">IRAF.net</a> is a more comprehensive resource with a searchable archive of previous IRAF questions.  It is now also a forum.
    <dt><a href="http://adswww.harvard.edu/">NASA Astrophysics Data Service </a>
    <!--    <dt><a href="http://arxiv.org/archive/astro-ph/">Astro-ph (arxiv.org)</a>-->
    <dt><a href="http://simbad.u-strasbg.fr/simbad/">SIMBAD Astronomical Database</a>
    <!--<dt><a href="http://nedwww.ipac.caltech.edu/">NASA/IPAC Extragalactic Database</a>-->
    <dt><a href="http://irsa.ipac.caltech.edu/">NASA/IPAC Infrared Science Archive</a> includes Digital Sky Survey, Sloan DSS, and 2MASS (infrared) finder charts
    <dt><a href="http://nedwww.ipac.caltech.edu/level5/Gray/Gray_contents.html"> A digital spectral classification atlas </a>
</dl>

            </table>

<br><br><br>
<?php include 'navbar.php';?>

</phtml>
